Repository modelica/ModelicaSpecification, pull requests merged in 2018-12, with the labels that each got.

#2296 This fixes the ugly table from section 7.1.3
  inheritance.tex
  preamble.tex
Labels: enhancement

#2291 Add Travis CI
  .travis.yml
  .travis_install.sh
  .travis_texlive.profile
  README.md
Labels: CI

#2299 Install multirow for Travis CI
  .travis_install.sh
Labels: CI

#2300 This is related to #2297 but is only restructuring the repo in a cleaner way.
  MLS.tex
  Makefile
  chapters/abstract.tex
  chapters/annotations.tex
  chapters/arrays.tex
  chapters/classes.tex
  chapters/connectors.tex
  chapters/dae.tex
  chapters/derivationofstream.tex
  chapters/equations.tex
  chapters/functions.tex
  chapters/glossary.tex
  chapters/inheritance.tex
  chapters/interface.tex
  chapters/introduction.tex
  chapters/lexicalstructure.tex
  chapters/library.tex
  chapters/literature.tex
  chapters/operatorsandexpressions.tex
  chapters/overloaded.tex
  chapters/packages.tex
  chapters/preface.tex
  chapters/revisions.tex
  chapters/scoping.tex
  chapters/statemachines.tex
  chapters/statements.tex
  chapters/stream.tex
  chapters/synchronous.tex
  chapters/syntax.tex
  chapters/unitexpressions.tex
  css/LaTeXML-maybeMathJax.js
  css/LaTeXML-navbar-left.css
  css/LaTeXML-navbar-right.css
  css/LaTeXML.css
  css/ltx-article.css
  css/ltx-listings.css
  css/ltx-report.css
  css/ltx-ulem.css
  preamble.tex
Labels: LaTeX
