Repository modelica/ModelicaSpecification, pull requests merged in 2019-06, with the labels that each got.

#2382 Remove Trailing WhiteSpace
  chapters/annotations.tex
  chapters/arrays.tex
  chapters/classes.tex
  chapters/connectors.tex
  chapters/dae.tex
  chapters/equations.tex
  chapters/functions.tex
  chapters/glossary.tex
  chapters/inheritance.tex
  chapters/interface.tex
  chapters/introduction.tex
  chapters/lexicalstructure.tex
  chapters/operatorsandexpressions.tex
  chapters/overloaded.tex
  chapters/packages.tex
  chapters/preface.tex
  chapters/revisions.tex
  chapters/statemachines.tex
  chapters/statements.tex
  chapters/stream.tex
  chapters/synchronous.tex
  chapters/syntax.tex
  chapters/unitexpressions.tex
Labels: LaTeX

#2383 Missing one chapter
  chapters/scoping.tex
Labels: LaTeX

#2361 Find files with trailing whitespace
  .CI/Jenkinsfile
Labels: CI

#2381 Update unitexpressions.tex
  chapters/unitexpressions.tex
Labels: English, P: low

#2384 Remove incorrect trailing underscore from Q-CHAR
  chapters/lexicalstructure.tex
Labels: bug
