Repository modelica/ModelicaSpecification, pull requests merged in 2020-11, with the labels that each got.

#2482 MCP-0033 Annotations for Predefined Plots
  RationaleMCP/0033/ReadMe.md
  RationaleMCP/0033/example-figure.png
  RationaleMCP/0033/predefined-plots.md
  chapters/annotations.tex
Labels: MCP0033

#2691 Improve definition of text markup escape sequences
  chapters/annotations.tex
  preamble.tex
Labels: MCP0033

#2710 Mcp/0033
  chapters/annotations.tex
  preamble.tex
Labels: MCP0033

#2694 Variability in record member declaration
  RationaleMCP/0031/differences.md
  RationaleMCP/0031/variability-constrained-types.md
Labels: MCP0031

#2725 Update to latexml 0.8.5
  .CI/Jenkinsfile
  .CI/latexml/Dockerfile.incremental
Labels: CI

#2728 Fix fortran77
  chapters/functions.tex
  mlsshared.sty
Labels: Generated HTML
