Repository modelica/ModelicaSpecification, pull requests merged in 2020-04, with the labels that each got.

#2537 Relax the uniqueness requirements of plot identifiers
  chapters/annotations.tex
Labels: MCP0033

#2478 Extend inverses, and slightly clarify.
  chapters/functions.tex
Labels: decided, discussion, enhancement

#2471 Description of handling of unknown dimensions added to differences.md
  RationaleMCP/0031/differences.md
Labels: MCP0031

#2546 Update to latexml 0.8.4
  .CI/Jenkinsfile
  .CI/latexml-iterative/Dockerfile
  .CI/latexml/Dockerfile
  chapters/derivationofstream.tex
Labels: CI

#2540 Update grammar.md
  RationaleMCP/0031/differences.md
  RationaleMCP/0031/grammar.md
Labels: MCP0031

#2545 New latex ml
  .CI/Jenkinsfile
  Makefile
  chapters/preface.tex
  chapters/scoping.tex
  css/LaTeXML-maybeMathJax.js
  css/LaTeXML-navbar-left.css
  css/LaTeXML-navbar-right.css
  css/LaTeXML.css
  css/ltx-article.css
  css/ltx-report.css
Labels: LaTeX
