Repository modelica/ModelicaSpecification, pull requests merged in 2020-02, with the labels that each got.

#2474 Minor cleanup of list of equation categories
  chapters/equations.tex
Labels: English

#2489 Revert regression for function arguments.
  chapters/functions.tex
  chapters/syntax.tex
Labels: regression

#2500 Use better logo files and remove old unused ones.
  MLS.tex
  chapters/abstract.tex
  media/Modelica_Language.pdf
  media/Modelica_Language.png
  media/image1 - Copy.png
  media/image1.pdf
Labels: LaTeX

#2501 Unify the url and fix copyright and registered mark.
  chapters/abstract.tex
  chapters/preface.tex
  chapters/revisions.tex
  preamble.tex
Labels: LaTeX

#2502 Updating dead links and also use DOI whenever possible.
  chapters/literature.tex
  chapters/revisions.tex
Labels: bug

#2504 Change SIunits to Units.SI as is the case as of MSL v4.0.0
  chapters/annotations.tex
  chapters/classes.tex
  chapters/connectors.tex
  chapters/inheritance.tex
  chapters/interface.tex
  chapters/operatorsandexpressions.tex
Labels: enhancement

#2505 Move the logo from abstract to title page
  chapters/abstract.tex
  preamble.tex
Labels: enhancement
