Repository modelica/ModelicaSpecification, pull requests merged in 2021-05, with the labels that each got.

#2927 Push builds to github-pages instead of SSH upload
  .CI/Jenkinsfile
Labels: CI

#2925 Push builds to github-pages instead of SSH upload
  .CI/Jenkinsfile
Labels: CI

#2926 Push builds to github-pages instead of SSH upload
  .CI/Jenkinsfile
Labels: CI

#2933 Do not use block links in the page header
  css/MLS.css
Labels: Generated HTML

#2934 Make the menu hover work on iOS Safari
  .CI/Jenkinsfile
  .scripts/patch-body-ios-hover.sh
  Makefile
Labels: CI, Generated HTML

#2939 Workaround for the markdown image not having ssh-agent
  .CI/Jenkinsfile
Labels: CI

#2936 Update README.md for balanced models.
  RationaleMCP/0009/README.md
Labels: MCP
