Repository modelica/ModelicaSpecification, pull requests merged in 2022-11, with the labels that each got.

#3167 Removing Modifications (MCP-0009)
  RationaleMCP/0009/README.md
  chapters/classes.tex
  chapters/inheritance.tex
  chapters/syntax.tex
Labels: MCP

#3166 Selective Model Extension (with specification text)
  RationaleMCP/0032/examples/SelectiveExtension_13th_Modelica_Conference 0.1.0.zip
  RationaleMCP/0032/examples/SelectiveExtension_13th_Modelica_Conference 0.2.0.zip
  RationaleMCP/0032/examples/SelectiveExtension_13th_Modelica_Conference 0.3.0.zip
  RationaleMCP/0032/examples/SelectiveExtension_13th_Modelica_Conference 0.4.0.zip
  RationaleMCP/0032/minutes.md
  RationaleMCP/0032/readme.md
  chapters/classes.tex
  chapters/functions.tex
  chapters/inheritance.tex
  chapters/syntax.tex
  mls.bib
Labels: MCP0032

#3231 Add clocked discrete-time expressions to discrete-time.
  chapters/operatorsandexpressions.tex
Labels: clocked

#3240 Simplify synchronous features
  RationaleMCP/0031/annotations.md
  RationaleMCP/0031/differences.md
  RationaleMCP/0031/grammar.md
Labels: MCP0031

#3258 Simplify when-equations
  RationaleMCP/0031/ReadMe.md
  RationaleMCP/0031/differences.md
Labels: MCP0031
